loan2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from services import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^/', include('services.urls')),
]

services/urls.py
from django.conf.urls import url
from services import views

app_name = 'services'

urlpatterns = [
    url(r'^about/$', views.about, name='about'),
    url(r'^vision/$', views.vision, name='vision'),
    url(r'^industry-structure/$', views.ind_str, name='ind_str'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^saving/$', views.saving, name='saving'),
    url(r'^recurring/$', views.recurring, name='recurring'),
    url(r'^monthlyincome/$', views.monthly, name='monthly'),
    url(r'^fixedDeposit/$', views.fixed, name='fixed'),
    url(r'^dailyDeposit/$', views.daily, name='daily'),
    url(r'^goldloan/$', views.gold, name='gold'),
    url(r'^grouploan/$', views.group, name='group'),
    url(r'^loan-against-deposit/$', views.loanagainstdeposit, name='loanagainstdeposit'),
    url(r'^loan-against-govt-securities/$', views.loanagainstgovtsec, name='loanagainstgovtsec'),
    url(r'^mortgage/$', views.mortgage, name='mortgage'),
    url(r'^personal/$', views.personal, name='personal'),
]

services/models.py
from django.db import models

# Create your models here.

services/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'services/index.html')

def about(request):
    return render(request, 'services/about.html')

def vision(request):
    return render(request, 'services/vision.html')

def ind_str(request):
    return render(request, 'services/industry_str.html')

def contact(request):
    return render(request, 'services/contact.html')

# schemes views
def saving(request):
    return render(request, 'services/schemes/saving.html')

def recurring(request):
    return render(request, 'services/schemes/recurring.html')

def monthly(request):
    return render(request, 'services/schemes/monthly.html')

def fixed(request):
    return render(request, 'services/schemes/fixed.html')

def daily(request):
    return render(request, 'services/schemes/daily.html')

# Loan views
def gold(request):
    return render(request, 'services/loans/gold.html')

def group(request):
    return render(request, 'services/loans/group.html')

def loanagainstdeposit(request):
    return render(request, 'services/loans/loanagainstdeposit.html')

def loanagainstgovtsec(request):
    return render(request, 'services/loans/loanagainstgovtsec.html')

def mortgage(request):
    return render(request, 'services/loans/mortgage.html')

def personal(request):
    return render(request, 'services/loans/personal.html')

templates/services/about.html
{% extends 'services/base.html' %}
{% block content %}
    <h1>About Us</h1>
    <div class="jumbotron" style="font-family:'Comic Sans MS', cursive, sans-serif; font-size:1.2em;">
        Citymore Nidhi Limited being a company registered under the Companies Act 2019, it automatically comes under the supervision of the MCA. Also being registered under the Company Act 2013 Citymore Nidhi Limited. Main objective is to encourage and afford all facilities for cultivating thrift ,saving habits and to render all financial assistance to its member only by receiving long and short term deposits and in particular recurring ,fixed and other deposits, not being current accounts from the members as are allowed by law for Nidhi or Mutual Benefits Companies and to grant loans to the members only as against securities, deposits and secured loan on properties of immovable properties (within City) and or on the security of deposits, movable such as gold and other Government securities up on such terms and condition as may from time to time prescribed in law for Nidhi or Mutual Benefits Companies.
        <br><br>
  A company declared as a Nidhi registered under the section 406 of the Companies Act, 2013. Nidhi is have many features which make them stand distinctly apart from many other Non-Banking financial company who are working under the guide line of R.B.I
        <br><br>
  Citymore Nidhi Limited has the rules and objectives of that are the same as a bank, but it is only in effect to someone (a members group) who has agreed or joined this agreement, as a bank, but to do business for Its Member only. So if the term is a quasi-bank, I think that the rules and objectives of that are the same like the commercial bank, but this thing are only in effect to someone (a members group) who has agree/join on this agreement. If a bank, but not the one honoured to do business for public. The way we provide service to our members is far better than others and we are trying to make it much better as our aim is to provide extreme level service to people as well as to our nation. Providing a world class financial support, Citymore Nidhi Limited. is continuously securing the society, we live in; on the other side, creating all new service method spontaneously Citymore Nidhi Limited is presenting a pleasant way which will help human being to lead the life comfortably. In a word we can say that Citymore Nidhi Limited is the "New Way Of Your Savings.</p>
    </div>
{% endblock %}

templates/services/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="CITYMORE NIDHI LIMITED being a company registered under the Companies Act 2013, it automatically comes under the supervision of the MCA. Also being registered under the Company Act 2013 CITYMORE NIDHI LIMITED.">
    <meta name="keywords" content="Nidhi Company, Loan Company, Deposit Scheme, RD, DDS, MIS, Fixed Deposit Plan, Recurring Deposit Plan, Saving Account, Monthly Income Scheme, Nidhi Govt. Bank, Nidhi Bank, Public Company, Share Holder Company, Mutual Benefits Company, Daily Deposit Scheme, Gold Loan, Loan Against Property, Mortgage Loan, RD Calculator, EMI Calculator, Loan Calculator, loan from nidhi in rewari, nidhi company in rewari, nidhi rewari, deposit in nidhi rewari ">
    <title>Citymore Nidhi Ltd.</title>
    <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">
    <!-- <link rel="shortcut icon" href="{% static 'images/arrowd.png' %}" type="image/x-icon"> -->
    <link rel="icon" href="images/favicon.png" type="image/x-icon">
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" >
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/fontello.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animsition.min.css' %}">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Merriweather:300,300i,400,400i,700,700i" rel="stylesheet">
    <!-- owl Carousel Css -->
    <link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.theme.css' %}" rel="stylesheet">

    <!-- css     -->
    <link href="{% static 'css/mycss.css' %}" rel="stylesheet">
  <!-- style start -->
    <!-- Bootstrap 3.3.2 -->
    <!-- <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"> -->
  <!-- <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css"> -->
    <!-- Bootstrap end -->
  <!-- style end -->

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/menumaker.js' %}"></script>
  <!-- animsition -->
  <script type="text/javascript" src="{% static 'js/animsition.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/animsition-script.js' %}"></script>
  <!-- sticky header -->
  <script type="text/javascript" src="{% static 'js/jquery.sticky.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/sticky-header.js' %}"></script>
  <!-- slider script -->
  <script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/slider-carousel.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/service-carousel.js' %}"></script>
  <!-- Back to top script -->
  <script src="{% static 'js/back-to-top.js' %}" type="text/javascript"></script>

  <script src="{% static 'js/handslid.js' %}" type="text/javascript"></script>
</head>

<body style='background-color:#fff'>
    <!-- /.top-bar -->

   <div class="header">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-12 col-xs-6">
                    <!-- logo -->
                    <div class="logo">
                        <a href="{% url 'index' %}"><img src="{% static 'images/Citymore board.jpg' %}" alt="Citymore Nidhi Limited"></a>
                    </div>
                </div>
                <!-- logo -->
                <div class="col-md-9 col-sm-12 col-xs-12">
                    <!-- /.navigation start-->
                      <!-- <div class="topnav"> -->
                        <div class='topnav-right'>
                          <div class="dropdown">
                            <strong><a href="{% url 'index' %}" class="ex">Home</a></strong>

                          </div>
                          <div class="dropdown">
                            <strong><a href="{% url 'services:about' %}" class="ex">About</a></strong>
                            <div class="dropdown-content">
                              <a href="{% url 'services:about' %}" title="About Company" class="animsition-link">About Company</a>
                              <a href="{% url 'services:vision' %}" title="Our Vision" class="animsition-link">Our Vision</a>
                              <a href="{% url 'services:vision' %}" title="Regularty" class="animsition-link">Regularty</a>
                              <a href="{% url 'services:ind_str' %}" title="Industry Structure" class="animsition-link">Industry Structure</a>
                            </div>
                          </div>
                          <div class="dropdown">
                              <strong><a href="#" class="ex">Schemes</a></strong>
                              <div class="dropdown-content">
                                <a href="{% url 'services:saving' %}" title="Saving Account">Saving Account</a>
                                <a href="{% url 'services:recurring' %}" title="Recurring Account">Recurring Account</a>
                                <a href="{% url 'services:monthly' %}" title="Monthly Income Scheme">Monthly Income Scheme</a>
                                <a href="{% url 'services:fixed' %}" title="Fixed Deposit Plan">Fixed Deposit Plan</a>
                                <a href="{% url 'services:daily' %}" title="Daily Deposit Scheme">Daily Deposit Scheme</a>
                              </div>
                          </div>
                          <div class="dropdown">
                            <strong><a href="#" class="ex">Loan</a></strong>
                            <div class="dropdown-content">
                              <a href="{% url 'services:gold' %}" title="Gold Loan" class="animsition-link">Gold Loan</a>
                              <a href="{% url 'services:group' %}" title="Group Loan" class="animsition-link">Group Loan</a>
                              <a href="{% url 'services:loanagainstdeposit' %}" title="Loan Against Deposit" class="animsition-link">Loan Against Deposit</a>
                              <a href="{% url 'services:loanagainstgovtsec' %}" title="Loan Against Govt. Security" class="animsition-link">Loan Against Govt. Security</a>
                              <a href="{% url 'services:mortgage' %}" title="Mortgage Loan" class="animsition-link">Mortgage Loan</a>
                              <a href="{% url 'services:personal' %}" title="Personal Loan" class="animsition-link">Personal Loan</a>
                            </div>
                          </div>
                          <div class="dropdown">
                            <strong><a href="{% url 'services:contact' %}" title="Contact us" class="ex">Contact us</a></strong>

                          </div>

                        <!-- </div> -->
                      </div>

                </div>
                <!-- search start-->
                <!--<div class="col-md-1 hidden-sm">

                    <div class="search-nav"> <a class="search-btn" role="button" data-toggle="collapse" href="searchbar" aria-expanded="false"><i class="fa fa-search"></i></a> </div>
                </div>-->
                <!-- /.search start-->
            </div>
        </div>
    </div>    <!----header page end ------>

    <div class="container">
      {% block content %}

      {% endblock %}
    </div>
    <!------Footer Page Start------>

      	<div class="footer">
          <!-- footer -->
          <div class="container">
              <div class="row">
                  <!--<div class="col-md-4 col-sm-4 col-xs-12">
                      <div class="footer-logo">

                          <img src="images/logo-1.png" alt="Swezo Nidhi Limited"> </div>

                  </div>-->
                  <div class="col-md-8 col-sm-8 col-xs-12">
                      <!--<div class="col-md-5">
                          <h3 class="newsletter-title" style="color:#fff">Signup Our Newsletter</h3>
                      </div>-->
                      <div class="col-md-7">
                          <!--<div class="newsletter-form">
                              <!-- Newsletter Form -->
                              <!--<form action="newsletter.php" method="post">
                                  <div class="input-group">
                                      <input type="email" class="form-control" id="newsletter" name="newsletter" placeholder="Write E-Mail Address" required>
                                      <span class="input-group-btn">
                  <button class="btn btn-default" type="submit">Go!</button>
                  </span> </div>
                                  <!-- /input-group --
                              </form>--
                          </div>-->
                          <!-- /.Newsletter Form -->
                      </div>
                      <!-- /.col-lg-6 -->
                  </div>
              </div>

          </div>
      </div>
      <!-- /.footer -->
      <div class="tiny-footer">
          <!-- tiny footer -->
          <div class="container">
              <div class="row">
                  <div class="col-md-6 col-sm-6 col-xs-6">
                      <p style="color:#fff">© Copyright 2019 | Citymore Nidhi Limited</p>
                  </div>
                  <div class="col-md-6 col-sm-6 text-right col-xs-6">
                      <p style="color:#fff">Terms of use | Privacy Policy</p>
                  </div>
              </div>
          </div>
      </div>
      <!------Footer Page End-------->
      <a href="#0" class="cd-top" title="Go to top">Top</a>

  </body>

  </html>

templates/services/contact.html
{% extends 'services/base.html' %}
{% load staticfiles %}
{% block content %}
<!-- <img src="{% static 'images/enquiry3.jpg' %}" alt="Citymore Enquiry" width="100%"> -->
<img src="{% static 'images/Citymore board.jpg' %}" alt="Citymore EnquiryAddress" width="100%">
<br><br><br><br>
<h1>Contact Us:</h1>
<div class="jumbotron">
  <h2><strong>Email: </strong>  suppport.citymore@gmail.com</h2>

</div>
{% endblock %}

templates/services/index.html
{% extends 'services/base.html' %}
<!-- {% load staticfiles %} -->
{% block content %}
<html>
  <head>
    <title>Citymore Nidhi Ltd</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
    <style>
    .mySlides {display:none;}
    </style>
  </head>
  <body>
    <!-- start -->
    <div class="slider" id="slider">
            <!-- slider -->

            <div class="slider-img"><img src="{% static 'images/family.jpg' %}" alt="Citymore Nidhi Limited" class="">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">


                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="slider-img"><img src="{% static 'images/schemes.jpg' %}" alt="Citymore Nidhi Limited" class="">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                <div class="slider-captions">
                                    <!-- slider-captions -->
                                    <!-- <h1 class="slider-title text-highlight" style="color:#000;">Loans are Available.<br>at Citymore Nidhi Limited</h1> -->
                                    <!-- <p class="slider-text hidden-xs" style="color:#000;"> We provide Loans. Visit us for more details.</p> -->
                                    <!-- <a href="#" class="btn btn-default hidden-xs" style="color:#000;">Check Eligiblity</a></div> -->
                                <!-- /.slider-captions -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div>

            </div>
        </div>
<!-- end -->
        <div class="section-space80">
            <div class="container">
              <!-- <div class="jumbotron"> -->
                <div class="row">
                    <!-- <div class="col-md-offset-2 col-md-8 col-sm-12 col-xs-12"> -->
                        <div class="mb20 text-center section-title">
                            <!-- section title start-->
                            <div class="jumbotron">
                              <h1>Find Loan Products We Offer</h1>
                              <p>We will match you with a loan program that meet your financial need. In short term liquidity, by striving to make funds available to them <strong>within 24 hours of application.</strong></p>
                            </div>

                        </div>
                        <!-- /.section title start-->
                    <!-- </div> -->
                </div>
              <!-- </div> -->

                <div class="row">
                    <div class="service" id="service">


                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="bg-white pinside40 service-block outline mb30">
                                <div class="icon mb40"> <img src="{% static 'images/deposit.png' %}" alt="Citymore Nidhi Limited" class="icon-svg-2x"></div>
                                  <h2>Loan Against Deposit</h2>
                                  <p style="font-family:'Comic Sans MS', cursive, sans-serif; font-size:1.2em;">Loan against deposit is given in the form of an overdraft against your deposited amount. This is an alternative given to you instead of breaking the deposit prematurely.<br><br></p>
                                  <a href="{% url 'services:loanagainstdeposit' %}" class="btn-link" target="_blank">Read More</a>
                            </div>
                        </div>
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="bg-white pinside40 service-block outline mb30">
                                <div class="icon mb40"> <img src="{% static 'images/gold.png' %}" alt="Citymore Nidhi Limited" class="icon-svg-2x"></div>
                                <h2>Gold Loan</h2>
                                <p style="font-family:'Comic Sans MS', cursive, sans-serif; font-size:1.2em;">Gold Loan offers you quick and easy financing at attractive interest rates. The loan pupose is to meet urgent financial needs. Any individual who is the true owner of the ornaments can apply for this loan.</p>
                                <a href="{% url 'services:gold' %}" class="btn-link" target="_blank">Read More</a>
                        </div>
                    </div>
                <div class="row">
                    <div class="service" id="service">

                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="bg-white pinside40 service-block outline mb30">
                                <div class="icon mb40"> <img src="{% static 'images/group.png' %}" alt="Citymore Nidhi Limited" class="icon-svg-2x"></div>
                                <h2>Group Loan</h2>
                                <p style="font-family:'Comic Sans MS', cursive, sans-serif; font-size:1.2em;">The group loan is a business credit facility that is designed to finance groups of 5 to 10 entrepreneurs. This loan is provided to groups of entrepreneurs with valid individual businesses. No collateral needed. Guarantorship from group members. </p>
                                <a href="{% url 'services:group' %}" class="btn-link" target="_blank">Read More</a>
                            </div
                        </div>
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="bg-white pinside40 service-block outline mb30">
                                <div class="icon mb40"> <img src="{% static 'images/personal.png' %}" alt="Citymore Nidhi Limited" class="icon-svg-2x"></div>
                                <h2>Personal Loan</h2>
                                <p style="font-family:'Comic Sans MS', cursive, sans-serif; font-size:1.2em;">For managing your finance and acts as an impetus in putting your plans into actions then a personal loan is a great tool for it. Our range of personal loans are simple and flexible, designed with your changing needs in mind. </p>
                                <a href="{% url 'services:personal' %}" class="btn-link" target="_blank">Read More</a>
                            </div>
                        </div>
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="bg-white pinside40 service-block outline mb30">
                                <div class="icon mb40"> <img src="{% static 'images/government.png' %}" alt="Citymore Nidhi Limited" class="icon-svg-2x"></div>
                                <h2>Loan Against Govt. Securities</h2>
                                <p style="font-family:'Comic Sans MS', cursive, sans-serif; font-size:1.2em;">Govt. securities, PSU Bonds, Securities/Relief Bonds issued by RBI/SBI/ICICI/IDBI, NSCs, LIC Policies of LIC of India or other such securities transferable/assignable to the Company.</p>
                                <a href="{% url 'services:loanagainstgovtsec' %}" class="btn-link" target="_blank">Read More</a>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>

        <div class="bg-white section-space80">
            <div class="container">
                <div class="row">
                    <div class="col-md-offset-2 col-md-8">
                        <div class="mb60 text-center section-title">

                            <h1>Our Schemes</h1>
                            <p style="font-family:'Comic Sans MS', cursive, sans-serif; font-size:1.2em;">We offer multiple types of schemes</p>
                        </div>

                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="bg-white">
                            <div class="row">
                                <div class="col-md-3 col-sm-6 nopadding col-xs-12">
                                    <div class="bg-white pinside60 number-block outline">
                                        <div class="mb20"><img src="{% static 'images/schemes/fd.png' %}"></div>
                                        <h3 title="Fixed Deposit">Fixed Deposit</h3>
                                        <!--<p>Fixed deposits are safer and more secure form of investments than other conventional modes of investments available in the market. </p>-->
                                        <a href="{% url 'services:fixed' %}" class="btn btn-outline mt20" target="_blank">Read More</a> </div>
                                </div>
                                <div class="col-md-3 col-sm-6 nopadding col-xs-12">
                                    <div class="bg-white pinside60 number-block outline">
                                        <div class="mb20"><img src="{% static 'images/schemes/rd.png' %}"></div>
                                        <h3 title="Recurring Deposit">Recurring&nbsp;Deposit</h3>
                                        <!--<p>Recurring Deposit (RD) is a special kind of term deposit by Nidhi which caters the need of saving for the members with a regular income by making them deposit a fixed amount regularly.</p>-->
                                        <a href="{% url 'services:recurring' %}" class="btn btn-outline mt20" target="_blank">Read More</a> </div>
                                </div>
                                <div class="col-md-3 col-sm-12 nopadding col-xs-12">
                                    <div class="bg-white pinside60 number-block outline">
                                        <div class="mb20"><img src="{% static 'images/schemes/sa2.png' %}"></div>
                                        <h3 title="Savings Account">Savings Account</h3>
                                        <!--<p> Savings accounts are the most common and popular account services; you would have already worked upon.</p>-->
                                        <a href="{% url 'services:saving' %}" class="btn btn-outline mt20" target="_blank">Read More</a> </div>
                                </div>
                                <div class="col-md-3 col-sm-6 nopadding col-xs-12">
                                    <div class="bg-white pinside60 number-block outline">
                                        <div class="mb20"><img src="{% static 'images/schemes/mis.png' %}"></div>
                                        <h3 title="Monthly Income Service">MIS</h3>
                                        <!--<p>Citymore Nidhi India Limited introduced one of the finest monthly income plan in Rewari with the coverage of good monthly income interest rates.</p>-->
                                        <a href="{% url 'services:monthly' %}" class="btn btn-outline mt20" target="_blank">Read More</a> </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.tiny footer -->
        <!-- back to top icon -->


  </body>
</html

{% endblock %}

templates/services/industry_str.html
{% extends 'services/base.html' %}
{% load staticfiles %}
{% block content %}
  <img src="{% static 'images/industry.png' %}" alt="Citymore Vision" width="100%">
  <div class="container">
    <h2>Industry Structure</h2>
    <img src="{% static 'images/pack-img.png' %}" alt="Industry Structure" align='centre'>
    </div>
{% endblock %}

templates/services/loans/gold.html
{% extends 'services/base.html' %}
{% load staticfiles %}
{% block content %}
  <img src="{% static 'images/loans/gold.jpg'%}" alt="Gold Loan">
  <h1>About Gold Loan</h1>
  <div class="jumbotron" style="font-family:'Comic Sans MS', cursive, sans-serif; font-size:1.3em;">
    We, at Citymore Nidhi Limited, understand our customer's needs and have three primary gold loan schemes to choose from. Our attractive interest rates, quick disbursal, multiple repayment options and value added benefits ensure a pleasant experience, make us our customer's first choice. We realise the emotional value of gold, and have in place, state of the art security surveillance infrastructure. When you pledge your gold with us, rest assured, it is in the safest hands. Come unlock the best value for your gold ornaments at any of our branches.

  </div>
  <h1>Features of Gold Loan</h1>
  <div class="jumbotron" style="font-family:'Comic Sans MS', cursive, sans-serif; font-size:1.3em;">
    <p>All loans are not created equal, Gold loan has become a great option for people to use.</p>
    <ol>
      <li><strong>Faster Loan: </strong> Hassle-free quick processing of loans.</li>
      <li><strong>Maximum Amount: </strong> Avail Loan upto 85% of Gold value.</li>
      <li><strong>Minimum Documentation: </strong> Minimum documentation and quick disbursal.</li>
      <li><strong>Less Paperwork: </strong> Simplified Paperwork.</li>
      <li><strong>Multiple Payment Options: </strong> Easy Payment Options.</li>
      <li><strong>ATL: </strong> ATL - Anytime Liquidity.</li>
    </ol>
  </div>
  <h1>Terms & Conditions</h1>
  <div class="jumbotron" style="font-family:'Comic Sans MS', cursive, sans-serif; font-size:1.3em;">
    <p>Terms & conditions of Gold Loans at Citymore Nidhi Limited are as follows.</p>
    <ol>
      <li>The loan tenure will be 3-12 months.</li>
      <li>The interest on your loan is fixed rate of interest and is mentioned on the sanction letter provided at the time of loan disbursement.</li>
      <li>The same is calculated per annum with monthly rate during tenure and payable upfront or monthly. Interest will be charged on a daily basis.</li>
      <li>Interest is to be paid on the due date as mentioned herein. Failure to pay interest on time will be an event of default and may lead to appopriate action by the company towards recovery of dues, including sale of gold, at the sole discretion of the company. In case of pre-payment or part payment, interest recovered upfront, shall not be refundable.</li>
      <li>Any default in payment of installment and/or other charges (if any) will lead to payment of additional interest as applicable for Temporary Overdraft (TOD) i.e. @ the rate of interest is 24% per annum.</li>
      <li>You shall be liable to pay the charges (panelty) as mentioned below which shall be payable upfront and shall be deducted from the sanctioned loan amount.</li>
    </ol>
  </div>
{% endblock %}

templates/services/schemes/monthly.html
{% extends 'services/base.html' %}
{% load staticfiles %}
{% block content %}
    <img src="{% static 'images/schemes/monthly.jpg'%}" alt="Monthly Income Scheme">
    <h1>Terms & Conditions</h1>
    <div class="jumbotron">
      <ol style="font-family:'Comic Sans MS', cursive, sans-serif; font-size:1.3em;">
        <li>Minimum MIS would be of  10000/- and futher in multiple of  10000/-</li>
        <li>No TDS Deducted on interest paid by Citymore Nidhi Limited on Deposit.</li>
        <li>pecial MIS is applicable only for Senior citizens.</li>
        <li>Loan available against Deposit up to 70% of deposited amount after one month from the date of deposit.</li>
      </ol>
    </div>

{% endblock %}